# ./netlify.toml  (en la raíz del repo)
[build]
  command = "npm run build"
  publish = "dist/pokemon-ssr/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  NODE_VERSION = "22"
